services:
  danbooru_channel_bot:
    image: ghcr.io/nachtalb/danbooruchannelbot:latest
    # build: .
    container_name: danbooru_channel_bot
    restart: unless-stopped
    env_file: .env
    # ports:
    #   - 5555:5555  # webhook mode
    volumes:
      - config:/config

volumes:
  config:
